In [1]:
!pip install boto3

Collecting boto3
  Downloading boto3-1.42.89-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.43.0,>=1.42.89 (from boto3)
  Downloading botocore-1.42.89-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\nada amalia\anaconda3\lib\site-packages (from boto3) (1.0.1)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\nada amalia\anaconda3\lib\site-packages (from botocore<1.43.0,>=1.42.89->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\nada amalia\anaconda3\lib\site-packages (from botocore<1.43.0,>=1.42.89->boto3) (2.2.2)
Requirement already satisfied: six>=1.5 in c:\users\nada amalia\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.89->boto3) (1.16.0)
Downloading boto3-1.42.89-py3-none-any.whl (140 kB)
   ---------------------------------------- 0.0/140.6 kB ? eta -:--:--
   ---------------------------------------- 0.0/140.6 kB ? eta -:--:--
   -- ------------------------------------- 10.2/140.6 kB ? eta -:--:--
   -- ------------------------------------- 10.2/140.6 kB ? eta -:--:--
   -------- ------------------------------ 30.7/140.6 kB 217.9 kB/s eta 0:00:01
   ----------------- --------------------- 61.4/140.6 kB 328.2 kB/s eta 0:00:01
   ------------------- ------------------- 71.7/140.6 kB 326.8 kB/s eta 0:00:01
   --------------------------- ---------- 102.4/140.6 kB 328.0 kB/s eta 0:00:01
   -------------------------------------- 140.6/140.6 kB 397.3 kB/s eta 0:00:00
Downloading botocore-1.42.89-py3-none-any.whl (14.9 MB)
   ---------------------------------------- 0.0/14.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.9 MB 1.3 MB/s eta 0:00:12
   ---------------------------------------- 0.1/14.9 MB 975.2 kB/s eta 0:00:16
   ---------------------------------------- 0.1/14.9 MB 1.0 MB/s eta 0:00:15
   ---------------------------------------- 0.2/14.9 MB 952.6 kB/s eta 0:00:16
    --------------------------------------- 0.2/14.9 MB 981.9 kB/s eta 0:00:15
    --------------------------------------- 0.3/14.9 MB 923.9 kB/s eta 0:00:16
    --------------------------------------- 0.3/14.9 MB 999.9 kB/s eta 0:00:15
    --------------------------------------- 0.3/14.9 MB 982.3 kB/s eta 0:00:15
   - -------------------------------------- 0.4/14.9 MB 1.0 MB/s eta 0:00:14
   - -------------------------------------- 0.5/14.9 MB 1.0 MB/s eta 0:00:15
   - -------------------------------------- 0.5/14.9 MB 1.0 MB/s eta 0:00:15
   - -------------------------------------- 0.6/14.9 MB 1.0 MB/s eta 0:00:14
   - -------------------------------------- 0.6/14.9 MB 1.1 MB/s eta 0:00:14
   -- ------------------------------------- 0.8/14.9 MB 1.2 MB/s eta 0:00:12
   -- ------------------------------------- 1.0/14.9 MB 1.4 MB/s eta 0:00:11
   -- ------------------------------------- 1.1/14.9 MB 1.5 MB/s eta 0:00:09
   --- ------------------------------------ 1.3/14.9 MB 1.6 MB/s eta 0:00:09
   --- ------------------------------------ 1.5/14.9 MB 1.8 MB/s eta 0:00:08
   ---- ----------------------------------- 1.6/14.9 MB 1.8 MB/s eta 0:00:08
   ---- ----------------------------------- 1.7/14.9 MB 1.8 MB/s eta 0:00:08
   ---- ----------------------------------- 1.8/14.9 MB 1.8 MB/s eta 0:00:08
   ---- ----------------------------------- 1.8/14.9 MB 1.8 MB/s eta 0:00:08
   ----- ---------------------------------- 1.9/14.9 MB 1.8 MB/s eta 0:00:08
   ----- ---------------------------------- 1.9/14.9 MB 1.8 MB/s eta 0:00:08
   ----- ---------------------------------- 2.0/14.9 MB 1.8 MB/s eta 0:00:08
   ----- ---------------------------------- 2.1/14.9 MB 1.7 MB/s eta 0:00:08
   ----- ---------------------------------- 2.1/14.9 MB 1.7 MB/s eta 0:00:08
   ----- ---------------------------------- 2.2/14.9 MB 1.7 MB/s eta 0:00:08
   ------ --------------------------------- 2.3/14.9 MB 1.7 MB/s eta 0:00:08
   ------ --------------------------------- 2.3/14.9 MB 1.7 MB/s eta 0:00:08
   ------ --------------------------------- 2.4/14.9 MB 1.6 MB/s eta 0:00:08
   ------ --------------------------------- 2.4/14.9 MB 1.6 MB/s eta 0:00:08
   ------ --------------------------------- 2.4/14.9 MB 1.6 MB/s eta 0:00:08
   ------ --------------------------------- 2.5/14.9 MB 1.6 MB/s eta 0:00:08
   ------ --------------------------------- 2.5/14.9 MB 1.6 MB/s eta 0:00:08
   ------ --------------------------------- 2.6/14.9 MB 1.6 MB/s eta 0:00:08
   ------- -------------------------------- 2.6/14.9 MB 1.6 MB/s eta 0:00:08
   ------- -------------------------------- 2.7/14.9 MB 1.5 MB/s eta 0:00:08
   ------- -------------------------------- 2.7/14.9 MB 1.5 MB/s eta 0:00:08
   ------- -------------------------------- 2.8/14.9 MB 1.5 MB/s eta 0:00:08
   ------- -------------------------------- 2.8/14.9 MB 1.5 MB/s eta 0:00:09
   ------- -------------------------------- 2.8/14.9 MB 1.5 MB/s eta 0:00:09
   ------- -------------------------------- 2.8/14.9 MB 1.5 MB/s eta 0:00:09
   ------- -------------------------------- 2.8/14.9 MB 1.5 MB/s eta 0:00:09
   ------- -------------------------------- 2.8/14.9 MB 1.5 MB/s eta 0:00:09
   ------- -------------------------------- 2.8/14.9 MB 1.5 MB/s eta 0:00:09
   ------- -------------------------------- 2.8/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.1/14.9 MB 1.4 MB/s eta 0:00:09
   -------- ------------------------------- 3.1/14.9 MB 1.4 MB/s eta 0:00:09
   -------- ------------------------------- 3.2/14.9 MB 1.4 MB/s eta 0:00:09
   -------- ------------------------------- 3.2/14.9 MB 1.4 MB/s eta 0:00:09
   -------- ------------------------------- 3.2/14.9 MB 1.3 MB/s eta 0:00:09
   -------- ------------------------------- 3.2/14.9 MB 1.3 MB/s eta 0:00:09
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:09
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:09
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/14.9 MB 1.3 MB/s eta 0:00:10
   --------- ------------------------------ 3.6/14.9 MB 1.1 MB/s eta 0:00:11
   --------- ------------------------------ 3.6/14.9 MB 1.1 MB/s eta 0:00:11
   --------- ------------------------------ 3.6/14.9 MB 1.1 MB/s eta 0:00:11
   --------- ------------------------------ 3.6/14.9 MB 1.1 MB/s eta 0:00:11
   --------- ------------------------------ 3.6/14.9 MB 1.1 MB/s eta 0:00:11
   --------- ------------------------------ 3.6/14.9 MB 1.0 MB/s eta 0:00:12
   --------- ------------------------------ 3.6/14.9 MB 1.0 MB/s eta 0:00:12
   --------- ------------------------------ 3.7/14.9 MB 1.0 MB/s eta 0:00:11
   ---------- ----------------------------- 3.8/14.9 MB 1.0 MB/s eta 0:00:11
   ---------- ----------------------------- 3.8/14.9 MB 1.0 MB/s eta 0:00:11
   ---------- ----------------------------- 3.8/14.9 MB 1.0 MB/s eta 0:00:11
   ---------- ----------------------------- 3.8/14.9 MB 1.0 MB/s eta 0:00:11
   ---------- ----------------------------- 3.8/14.9 MB 980.4 kB/s eta 0:00:12
   ---------- ----------------------------- 3.8/14.9 MB 977.6 kB/s eta 0:00:12
   ---------- ----------------------------- 3.8/14.9 MB 977.6 kB/s eta 0:00:12
   ---------- ----------------------------- 3.8/14.9 MB 977.6 kB/s eta 0:00:12
   ---------- ----------------------------- 3.8/14.9 MB 977.6 kB/s eta 0:00:12
   ---------- ----------------------------- 3.8/14.9 MB 977.6 kB/s eta 0:00:12
   ---------- ----------------------------- 3.8/14.9 MB 977.6 kB/s eta 0:00:12
   ---------- ----------------------------- 3.9/14.9 MB 934.0 kB/s eta 0:00:12
   ---------- ----------------------------- 3.9/14.9 MB 935.6 kB/s eta 0:00:12
   ---------- ----------------------------- 3.9/14.9 MB 935.6 kB/s eta 0:00:12
   ---------- ----------------------------- 3.9/14.9 MB 935.6 kB/s eta 0:00:12
   ---------- ----------------------------- 3.9/14.9 MB 935.6 kB/s eta 0:00:12
   ---------- ----------------------------- 3.9/14.9 MB 935.6 kB/s eta 0:00:12
   ---------- ----------------------------- 4.0/14.9 MB 893.6 kB/s eta 0:00:13
   ---------- ----------------------------- 4.0/14.9 MB 888.9 kB/s eta 0:00:13
   ---------- ----------------------------- 4.0/14.9 MB 888.9 kB/s eta 0:00:13
   ---------- ----------------------------- 4.1/14.9 MB 877.4 kB/s eta 0:00:13
   ---------- ----------------------------- 4.1/14.9 MB 877.4 kB/s eta 0:00:13
   ---------- ----------------------------- 4.1/14.9 MB 867.2 kB/s eta 0:00:13
   ---------- ----------------------------- 4.1/14.9 MB 858.0 kB/s eta 0:00:13
   ----------- ---------------------------- 4.1/14.9 MB 853.9 kB/s eta 0:00:13
   ----------- ---------------------------- 4.1/14.9 MB 853.9 kB/s eta 0:00:13
   ----------- ---------------------------- 4.1/14.9 MB 847.0 kB/s eta 0:00:13
   ----------- ---------------------------- 4.1/14.9 MB 841.0 kB/s eta 0:00:13
   ----------- ---------------------------- 4.1/14.9 MB 841.0 kB/s eta 0:00:13
   ----------- ---------------------------- 4.2/14.9 MB 826.8 kB/s eta 0:00:13
   ----------- ---------------------------- 4.2/14.9 MB 821.1 kB/s eta 0:00:14
   ----------- ---------------------------- 4.2/14.9 MB 815.2 kB/s eta 0:00:14
   ----------- ---------------------------- 4.2/14.9 MB 815.2 kB/s eta 0:00:14
   ----------- ---------------------------- 4.2/14.9 MB 806.9 kB/s eta 0:00:14
   ----------- ---------------------------- 4.2/14.9 MB 799.2 kB/s eta 0:00:14
   ----------- ---------------------------- 4.2/14.9 MB 799.2 kB/s eta 0:00:14
   ----------- ---------------------------- 4.2/14.9 MB 791.4 kB/s eta 0:00:14
   ----------- ---------------------------- 4.2/14.9 MB 791.4 kB/s eta 0:00:14
   ----------- ---------------------------- 4.2/14.9 MB 791.4 kB/s eta 0:00:14
   ----------- ---------------------------- 4.2/14.9 MB 777.4 kB/s eta 0:00:14
   ----------- ---------------------------- 4.3/14.9 MB 774.5 kB/s eta 0:00:14
   ----------- ---------------------------- 4.3/14.9 MB 774.5 kB/s eta 0:00:14
   ----------- ---------------------------- 4.3/14.9 MB 774.5 kB/s eta 0:00:14
   ----------- ---------------------------- 4.3/14.9 MB 774.5 kB/s eta 0:00:14
   ----------- ---------------------------- 4.3/14.9 MB 774.5 kB/s eta 0:00:14
   ----------- ---------------------------- 4.3/14.9 MB 774.5 kB/s eta 0:00:14
   ----------- ---------------------------- 4.3/14.9 MB 774.5 kB/s eta 0:00:14
   ----------- ---------------------------- 4.3/14.9 MB 735.9 kB/s eta 0:00:15
   ----------- ---------------------------- 4.3/14.9 MB 733.5 kB/s eta 0:00:15
   ----------- ---------------------------- 4.4/14.9 MB 731.2 kB/s eta 0:00:15
   ----------- ---------------------------- 4.4/14.9 MB 731.2 kB/s eta 0:00:15
   ----------- ---------------------------- 4.4/14.9 MB 723.4 kB/s eta 0:00:15
   ----------- ---------------------------- 4.4/14.9 MB 721.2 kB/s eta 0:00:15
   ----------- ---------------------------- 4.4/14.9 MB 715.2 kB/s eta 0:00:15
   ----------- ---------------------------- 4.4/14.9 MB 714.9 kB/s eta 0:00:15
   ----------- ---------------------------- 4.5/14.9 MB 712.8 kB/s eta 0:00:15
   ------------ --------------------------- 4.5/14.9 MB 712.3 kB/s eta 0:00:15
   ------------ --------------------------- 4.5/14.9 MB 712.0 kB/s eta 0:00:15
   ------------ --------------------------- 4.5/14.9 MB 711.6 kB/s eta 0:00:15
   ------------ --------------------------- 4.6/14.9 MB 712.8 kB/s eta 0:00:15
   ------------ --------------------------- 4.6/14.9 MB 715.3 kB/s eta 0:00:15
   ------------ --------------------------- 4.7/14.9 MB 718.4 kB/s eta 0:00:15
   ------------ --------------------------- 4.7/14.9 MB 719.3 kB/s eta 0:00:15
   ------------ --------------------------- 4.8/14.9 MB 721.9 kB/s eta 0:00:14
   ------------ --------------------------- 4.8/14.9 MB 723.0 kB/s eta 0:00:14
   ------------- -------------------------- 4.9/14.9 MB 724.1 kB/s eta 0:00:14
   ------------- -------------------------- 4.9/14.9 MB 728.2 kB/s eta 0:00:14
   ------------- -------------------------- 5.0/14.9 MB 730.7 kB/s eta 0:00:14
   ------------- -------------------------- 5.0/14.9 MB 734.6 kB/s eta 0:00:14
   ------------- -------------------------- 5.1/14.9 MB 737.1 kB/s eta 0:00:14
   ------------- -------------------------- 5.1/14.9 MB 739.4 kB/s eta 0:00:14
   ------------- -------------------------- 5.2/14.9 MB 741.8 kB/s eta 0:00:14
   -------------- ------------------------- 5.2/14.9 MB 742.9 kB/s eta 0:00:14
   -------------- ------------------------- 5.3/14.9 MB 742.2 kB/s eta 0:00:13
   -------------- ------------------------- 5.3/14.9 MB 743.4 kB/s eta 0:00:13
   -------------- ------------------------- 5.3/14.9 MB 741.6 kB/s eta 0:00:13
   -------------- ------------------------- 5.3/14.9 MB 737.9 kB/s eta 0:00:13
   -------------- ------------------------- 5.3/14.9 MB 736.0 kB/s eta 0:00:13
   -------------- ------------------------- 5.3/14.9 MB 732.6 kB/s eta 0:00:14
   -------------- ------------------------- 5.4/14.9 MB 729.0 kB/s eta 0:00:14
   -------------- ------------------------- 5.4/14.9 MB 729.0 kB/s eta 0:00:14
   -------------- ------------------------- 5.4/14.9 MB 728.5 kB/s eta 0:00:14
   -------------- ------------------------- 5.4/14.9 MB 726.8 kB/s eta 0:00:14
   -------------- ------------------------- 5.5/14.9 MB 721.8 kB/s eta 0:00:14
   -------------- ------------------------- 5.5/14.9 MB 717.2 kB/s eta 0:00:14
   -------------- ------------------------- 5.5/14.9 MB 718.5 kB/s eta 0:00:14
   -------------- ------------------------- 5.5/14.9 MB 715.4 kB/s eta 0:00:14
   -------------- ------------------------- 5.5/14.9 MB 713.7 kB/s eta 0:00:14
   -------------- ------------------------- 5.6/14.9 MB 711.9 kB/s eta 0:00:14
   -------------- ------------------------- 5.6/14.9 MB 710.2 kB/s eta 0:00:14
   --------------- ------------------------ 5.6/14.9 MB 711.3 kB/s eta 0:00:14
   --------------- ------------------------ 5.7/14.9 MB 716.1 kB/s eta 0:00:13
   --------------- ------------------------ 5.7/14.9 MB 717.0 kB/s eta 0:00:13
   --------------- ------------------------ 5.8/14.9 MB 725.3 kB/s eta 0:00:13
   --------------- ------------------------ 5.9/14.9 MB 730.2 kB/s eta 0:00:13
   ---------------- ----------------------- 6.0/14.9 MB 736.0 kB/s eta 0:00:13
   ---------------- ----------------------- 6.1/14.9 MB 739.3 kB/s eta 0:00:12
   ---------------- ----------------------- 6.1/14.9 MB 741.3 kB/s eta 0:00:12
   ---------------- ----------------------- 6.2/14.9 MB 743.3 kB/s eta 0:00:12
   ---------------- ----------------------- 6.2/14.9 MB 743.0 kB/s eta 0:00:12
   ---------------- ----------------------- 6.2/14.9 MB 741.4 kB/s eta 0:00:12
   ---------------- ----------------------- 6.2/14.9 MB 740.6 kB/s eta 0:00:12
   ---------------- ----------------------- 6.3/14.9 MB 741.5 kB/s eta 0:00:12
   ---------------- ----------------------- 6.3/14.9 MB 741.0 kB/s eta 0:00:12
   ----------------- ---------------------- 6.3/14.9 MB 742.9 kB/s eta 0:00:12
   ----------------- ---------------------- 6.4/14.9 MB 742.5 kB/s eta 0:00:12
   ----------------- ---------------------- 6.5/14.9 MB 745.4 kB/s eta 0:00:12
   ----------------- ---------------------- 6.5/14.9 MB 744.9 kB/s eta 0:00:12
   ----------------- ---------------------- 6.5/14.9 MB 746.6 kB/s eta 0:00:12
   ----------------- ---------------------- 6.6/14.9 MB 750.8 kB/s eta 0:00:12
   ----------------- ---------------------- 6.7/14.9 MB 756.1 kB/s eta 0:00:11
   ------------------ --------------------- 6.8/14.9 MB 761.3 kB/s eta 0:00:11
   ------------------ --------------------- 6.8/14.9 MB 765.5 kB/s eta 0:00:11
   ------------------ --------------------- 6.9/14.9 MB 767.2 kB/s eta 0:00:11
   ------------------ --------------------- 6.9/14.9 MB 768.9 kB/s eta 0:00:11
   ------------------ --------------------- 7.0/14.9 MB 771.7 kB/s eta 0:00:11
   ------------------ --------------------- 7.1/14.9 MB 774.5 kB/s eta 0:00:11
   ------------------- -------------------- 7.1/14.9 MB 778.3 kB/s eta 0:00:10
   ------------------- -------------------- 7.2/14.9 MB 784.4 kB/s eta 0:00:10
   ------------------- -------------------- 7.3/14.9 MB 788.2 kB/s eta 0:00:10
   ------------------- -------------------- 7.3/14.9 MB 787.5 kB/s eta 0:00:10
   ------------------- -------------------- 7.4/14.9 MB 789.3 kB/s eta 0:00:10
   ------------------- -------------------- 7.4/14.9 MB 786.2 kB/s eta 0:00:10
   ------------------- -------------------- 7.4/14.9 MB 785.8 kB/s eta 0:00:10
   -------------------- ------------------- 7.4/14.9 MB 783.8 kB/s eta 0:00:10
   -------------------- ------------------- 7.5/14.9 MB 785.3 kB/s eta 0:00:10
   -------------------- ------------------- 7.5/14.9 MB 786.9 kB/s eta 0:00:10
   -------------------- ------------------- 7.6/14.9 MB 788.3 kB/s eta 0:00:10
   -------------------- ------------------- 7.6/14.9 MB 790.0 kB/s eta 0:00:10
   -------------------- ------------------- 7.7/14.9 MB 792.3 kB/s eta 0:00:10
   -------------------- ------------------- 7.7/14.9 MB 790.8 kB/s eta 0:00:10
   -------------------- ------------------- 7.8/14.9 MB 791.2 kB/s eta 0:00:10
   -------------------- ------------------- 7.8/14.9 MB 789.8 kB/s eta 0:00:10
   -------------------- ------------------- 7.8/14.9 MB 787.9 kB/s eta 0:00:09
   --------------------- ------------------ 7.8/14.9 MB 788.2 kB/s eta 0:00:09
   --------------------- ------------------ 7.9/14.9 MB 786.6 kB/s eta 0:00:09
   --------------------- ------------------ 7.9/14.9 MB 788.2 kB/s eta 0:00:09
   --------------------- ------------------ 8.0/14.9 MB 788.5 kB/s eta 0:00:09
   --------------------- ------------------ 8.0/14.9 MB 789.6 kB/s eta 0:00:09
   --------------------- ------------------ 8.1/14.9 MB 791.0 kB/s eta 0:00:09
   --------------------- ------------------ 8.1/14.9 MB 794.6 kB/s eta 0:00:09
   ---------------------- ----------------- 8.2/14.9 MB 797.0 kB/s eta 0:00:09
   ---------------------- ----------------- 8.2/14.9 MB 798.3 kB/s eta 0:00:09
   ---------------------- ----------------- 8.3/14.9 MB 801.6 kB/s eta 0:00:09
   ---------------------- ----------------- 8.4/14.9 MB 802.9 kB/s eta 0:00:09
   ---------------------- ----------------- 8.4/14.9 MB 804.3 kB/s eta 0:00:09
   ---------------------- ----------------- 8.5/14.9 MB 805.7 kB/s eta 0:00:08
   ---------------------- ----------------- 8.5/14.9 MB 805.0 kB/s eta 0:00:08
   ----------------------- ---------------- 8.6/14.9 MB 807.1 kB/s eta 0:00:08
   ----------------------- ---------------- 8.6/14.9 MB 808.3 kB/s eta 0:00:08
   ----------------------- ---------------- 8.7/14.9 MB 810.8 kB/s eta 0:00:08
   ----------------------- ---------------- 8.7/14.9 MB 812.7 kB/s eta 0:00:08
   ----------------------- ---------------- 8.8/14.9 MB 814.9 kB/s eta 0:00:08
   ----------------------- ---------------- 8.8/14.9 MB 817.5 kB/s eta 0:00:08

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.12.3 requires botocore<1.34.70,>=1.34.41, but you have botocore 1.42.89 which is incompatible.

In [10]:
import pandas as pd
import boto3
import os
from dotenv import load_dotenv
from io import StringIO

In [13]:
data = pd.read_csv('../data/raw/news.csv') 
data.head()

,id,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [ ]:
# preprocessing dasar
X = data['text'].astype(str)
y = data['label'].map({'FAKE': 1, 'REAL': 0})

In [15]:
cleaned_data = pd.DataFrame({
    "text": X,
    "label": y
    })

cleaned_data.head()

                                                text  label
0  Daniel Greenfield, a Shillman Journalism Fello...      1
1  Google Pinterest Digg Linkedin Reddit Stumbleu...      1
2  U.S. Secretary of State John F. Kerry said Mon...      0
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...      1
4  It's primary day in New York and front-runners...      0

In [16]:
cleaned_data.to_csv("../data/processed/data_cleaned.csv", index=False)
print("Saved cleaned data to data_cleaned.csv")

Saved cleaned data to data_cleaned.csv

In [12]:
load_dotenv()
s3 = boto3.client(
    's3',
    aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
    region_name=os.getenv("AWS_DEFAULT_REGION")
)

bucket_name = os.getenv("S3_BUCKET_NAME")
key = "processed/data_cleaned.csv"

csv_buffer = StringIO()
data.to_csv(csv_buffer, index=False)

s3.put_object(Bucket=bucket_name, Key=key, Body=csv_buffer.getvalue())
print("Upload ke S3 berhasil!")

Upload ke S3 berhasil!