In [ ]:
!pip install boto3

In [5]:
import pandas as pd
import boto3
import os
from dotenv import load_dotenv
from io import StringIO

In [6]:
data = pd.read_csv('../data/raw/news.csv') 
data.head()

,id,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6335 entries, 0 to 6334
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      6335 non-null   int64
 1   title   6335 non-null   object
 2   text    6335 non-null   object
 3   label   6335 non-null   object
dtypes: int64(1), object(3)
memory usage: 198.1+ KB

In [8]:
# preprocessing dasar
X = data['text'].astype(str)
y = data['label'].map({'FAKE': 1, 'REAL': 0})

In [9]:
cleaned_data = pd.DataFrame({
    "text": X,
    "label": y
    })

cleaned_data.head()

                                                text  label
0  Daniel Greenfield, a Shillman Journalism Fello...      1
1  Google Pinterest Digg Linkedin Reddit Stumbleu...      1
2  U.S. Secretary of State John F. Kerry said Mon...      0
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...      1
4  It's primary day in New York and front-runners...      0

In [10]:
cleaned_data.to_csv("../data/processed/data_cleaned.csv", index=False)
print("Saved cleaned data to data_cleaned.csv")

Saved cleaned data to data_cleaned.csv

In [11]:
load_dotenv()
s3 = boto3.client(
    's3',
    aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
    region_name=os.getenv("AWS_DEFAULT_REGION")
)

bucket_name = os.getenv("S3_BUCKET_NAME")
key = "processed/data_cleaned.csv"

csv_buffer = StringIO()
data.to_csv(csv_buffer, index=False)

s3.put_object(Bucket=bucket_name, Key=key, Body=csv_buffer.getvalue())
print("Upload ke S3 berhasil!")

Upload ke S3 berhasil!